http://localhost:8787/api/private/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.k0E4fCFP1VDoTcpmlvKekVYldTCQCb2NQVQICz-HSAM

###
PUT http://localhost:8787/user
content-type: application/json

{
  "id" : 1,
  "caption" : "SACRED",
  "description" : "TEST"
}